### ISSUE TITLE
How do I get annotation.csv file?

### ISSUE THREAD

**Issue by nfyjmkdflq** [yuchengml/MTC#1]

**Comment by yuchengml** [comment]
About the annotation of the ISCX VPN-non VPN dataset, we referred to the three kinds of labels in Table 1 to annotate each file(*.pcap/*.pcapng) by ourselves due to the lack of information in the original paper.
It would look like this:
file | traffic_class | application_class | auxiliary_class
-- | -- | -- | --
aim_chat_3a.pcap | chat | aim_chat | all_chat

**Comment by nfyjmkdflq** [comment]
Ok, thank you for your reply. It helps me a lot.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年4月22日(星期一) 晚上11:37
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [yuchengml/MTC] How do I get annotation.csv file? (Issue #1)














 
About the annotation of the ISCX VPN-non VPN dataset, we referred to the three kinds of labels in Table 1 to annotate each file(.pcap/.pcapng) by ourselves due to the lack of information in the original paper.
 It would look like this:
    file traffic_class application_class auxiliary_class 
    aim_chat_3a.pcap chat aim_chat all_chat

**Comment by shanshan2chuan** [comment]
Could you please tell me how to get the annotation.csv file in more detail? Thank you.
